name: Dev CI

on:
  push:
    branches:
      - main

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint checks in packages
        run: |
          npm run lint:check

      - name: Run unit tests
        run: |
          npm run test
